development:
  adapter: redis
  url: redis://localhost:6360/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6360/1" } %>
  channel_prefix: OnlineStoryTelling_production
